updated init file

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -1,10 +1,15 @@
 #!/bin/sh
 
-echo "Halo OS initramfs starting..."
+echo "nextOS initramfs starting..."
 
-mount -t proc none /proc
-mount -t sysfs none /sys
-mount -t devtmpfs none /dev
+mount -t proc none /proc || echo "Failed to mount /proc"
+mount -t sysfs none /sys || echo "Failed to mount /sys"
+mount -t devtmpfs none /dev || echo "Failed to mount /dev"
+
+
+# Create essential devices if missing
+[ -e /dev/console ] || mkdir /dev/console c 5 1
+[ -e /def/null ] || mkdie /dev/null c 1 3
 
 echo "Initramfs environment ready"
 echo "Dropping to shell..."
